// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.6
// source: Shared/proto/block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta     *BlockMeta       `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Rules    *BlockRules      `protobuf:"bytes,2,opt,name=rules,proto3" json:"rules,omitempty"`
	Lang     string           `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Elements []*Block_Element `protobuf:"bytes,4,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetMeta() *BlockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Block) GetRules() *BlockRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Block) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Block) GetElements() []*Block_Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type BlockMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId    string   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Type       string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Tags       []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Categories []string `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockMeta) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlockMeta) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BlockMeta) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type BlockRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasLikes     *bool                    `protobuf:"varint,3,opt,name=has_likes,json=hasLikes,proto3,oneof" json:"has_likes,omitempty"`
	HasComments  *bool                    `protobuf:"varint,4,opt,name=has_comments,json=hasComments,proto3,oneof" json:"has_comments,omitempty"`
	CommentRules *BlockRules_CommentRules `protobuf:"bytes,5,opt,name=commentRules,proto3,oneof" json:"commentRules,omitempty"`
}

func (x *BlockRules) Reset() {
	*x = BlockRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRules) ProtoMessage() {}

func (x *BlockRules) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRules.ProtoReflect.Descriptor instead.
func (*BlockRules) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{2}
}

func (x *BlockRules) GetHasLikes() bool {
	if x != nil && x.HasLikes != nil {
		return *x.HasLikes
	}
	return false
}

func (x *BlockRules) GetHasComments() bool {
	if x != nil && x.HasComments != nil {
		return *x.HasComments
	}
	return false
}

func (x *BlockRules) GetCommentRules() *BlockRules_CommentRules {
	if x != nil {
		return x.CommentRules
	}
	return nil
}

type Block_Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Key   string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Block_Element) Reset() {
	*x = Block_Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Element) ProtoMessage() {}

func (x *Block_Element) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Element.ProtoReflect.Descriptor instead.
func (*Block_Element) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Block_Element) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block_Element) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block_Element) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Block_Element) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BlockRules_CommentRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nested    *bool  `protobuf:"varint,1,opt,name=nested,proto3,oneof" json:"nested,omitempty"`
	HasLikes  *bool  `protobuf:"varint,2,opt,name=has_likes,json=hasLikes,proto3,oneof" json:"has_likes,omitempty"`
	Editable  *bool  `protobuf:"varint,3,opt,name=editable,proto3,oneof" json:"editable,omitempty"`
	MaxNested *int32 `protobuf:"varint,4,opt,name=max_nested,json=maxNested,proto3,oneof" json:"max_nested,omitempty"`
}

func (x *BlockRules_CommentRules) Reset() {
	*x = BlockRules_CommentRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRules_CommentRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRules_CommentRules) ProtoMessage() {}

func (x *BlockRules_CommentRules) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRules_CommentRules.ProtoReflect.Descriptor instead.
func (*BlockRules_CommentRules) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BlockRules_CommentRules) GetNested() bool {
	if x != nil && x.Nested != nil {
		return *x.Nested
	}
	return false
}

func (x *BlockRules_CommentRules) GetHasLikes() bool {
	if x != nil && x.HasLikes != nil {
		return *x.HasLikes
	}
	return false
}

func (x *BlockRules_CommentRules) GetEditable() bool {
	if x != nil && x.Editable != nil {
		return *x.Editable
	}
	return false
}

func (x *BlockRules_CommentRules) GetMaxNested() int32 {
	if x != nil && x.MaxNested != nil {
		return *x.MaxNested
	}
	return 0
}

var File_Shared_proto_block_proto protoreflect.FileDescriptor

var file_Shared_proto_block_proto_rawDesc = []byte{
	0x0a, 0x18, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x30,
	0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x1a, 0x55, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6e, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x22, 0x99, 0x03, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69,
	0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01,
	0x52, 0x0b, 0x68, 0x61, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x47, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x02, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x88, 0x01, 0x01, 0x1a, 0xc7, 0x01, 0x0a, 0x0c, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x6e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x6c,
	0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x08, 0x68, 0x61,
	0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x65, 0x64, 0x69,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x08, 0x65,
	0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6d, 0x61,
	0x78, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03,
	0x52, 0x09, 0x6d, 0x61, 0x78, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x68, 0x61,
	0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x64, 0x69, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Shared_proto_block_proto_rawDescOnce sync.Once
	file_Shared_proto_block_proto_rawDescData = file_Shared_proto_block_proto_rawDesc
)

func file_Shared_proto_block_proto_rawDescGZIP() []byte {
	file_Shared_proto_block_proto_rawDescOnce.Do(func() {
		file_Shared_proto_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_Shared_proto_block_proto_rawDescData)
	})
	return file_Shared_proto_block_proto_rawDescData
}

var file_Shared_proto_block_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Shared_proto_block_proto_goTypes = []interface{}{
	(*Block)(nil),                   // 0: proto.Block
	(*BlockMeta)(nil),               // 1: proto.BlockMeta
	(*BlockRules)(nil),              // 2: proto.BlockRules
	(*Block_Element)(nil),           // 3: proto.Block.Element
	(*BlockRules_CommentRules)(nil), // 4: proto.BlockRules.CommentRules
}
var file_Shared_proto_block_proto_depIdxs = []int32{
	1, // 0: proto.Block.meta:type_name -> proto.BlockMeta
	2, // 1: proto.Block.rules:type_name -> proto.BlockRules
	3, // 2: proto.Block.elements:type_name -> proto.Block.Element
	4, // 3: proto.BlockRules.commentRules:type_name -> proto.BlockRules.CommentRules
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Shared_proto_block_proto_init() }
func file_Shared_proto_block_proto_init() {
	if File_Shared_proto_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Shared_proto_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block_Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRules_CommentRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Shared_proto_block_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_Shared_proto_block_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Shared_proto_block_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Shared_proto_block_proto_goTypes,
		DependencyIndexes: file_Shared_proto_block_proto_depIdxs,
		MessageInfos:      file_Shared_proto_block_proto_msgTypes,
	}.Build()
	File_Shared_proto_block_proto = out.File
	file_Shared_proto_block_proto_rawDesc = nil
	file_Shared_proto_block_proto_goTypes = nil
	file_Shared_proto_block_proto_depIdxs = nil
}
