// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.6
// source: Shared/proto/block.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId    string          `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Type       string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Lang       string          `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Tags       []string        `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Categories []string        `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	Authors    []*Block_Author `protobuf:"bytes,6,rep,name=authors,proto3" json:"authors,omitempty"`
	Content    []*Element      `protobuf:"bytes,7,rep,name=content,proto3" json:"content,omitempty"`
	Rules      *BlockRules     `protobuf:"bytes,8,opt,name=rules,proto3" json:"rules,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Block) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Block) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Block) GetAuthors() []*Block_Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Block) GetContent() []*Element {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Block) GetRules() *BlockRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type BlockContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang    string     `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Content []*Element `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *BlockContent) Reset() {
	*x = BlockContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockContent) ProtoMessage() {}

func (x *BlockContent) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockContent.ProtoReflect.Descriptor instead.
func (*BlockContent) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockContent) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *BlockContent) GetContent() []*Element {
	if x != nil {
		return x.Content
	}
	return nil
}

type BlockMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId    string              `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Type       string              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Tags       []string            `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Categories []string            `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	Authors    []*BlockMeta_Author `protobuf:"bytes,5,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{2}
}

func (x *BlockMeta) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockMeta) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlockMeta) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BlockMeta) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *BlockMeta) GetAuthors() []*BlockMeta_Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type BlockRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasLikes     *bool                    `protobuf:"varint,3,opt,name=has_likes,json=hasLikes,proto3,oneof" json:"has_likes,omitempty"`
	HasComments  *bool                    `protobuf:"varint,4,opt,name=has_comments,json=hasComments,proto3,oneof" json:"has_comments,omitempty"`
	CommentRules *BlockRules_CommentRules `protobuf:"bytes,5,opt,name=commentRules,proto3,oneof" json:"commentRules,omitempty"`
}

func (x *BlockRules) Reset() {
	*x = BlockRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRules) ProtoMessage() {}

func (x *BlockRules) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRules.ProtoReflect.Descriptor instead.
func (*BlockRules) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{3}
}

func (x *BlockRules) GetHasLikes() bool {
	if x != nil && x.HasLikes != nil {
		return *x.HasLikes
	}
	return false
}

func (x *BlockRules) GetHasComments() bool {
	if x != nil && x.HasComments != nil {
		return *x.HasComments
	}
	return false
}

func (x *BlockRules) GetCommentRules() *BlockRules_CommentRules {
	if x != nil {
		return x.CommentRules
	}
	return nil
}

type Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Element:
	//
	//	*Element_Image_
	//	*Element_Text_
	//	*Element_RichText_
	Element isElement_Element `protobuf_oneof:"element"`
}

func (x *Element) Reset() {
	*x = Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{4}
}

func (m *Element) GetElement() isElement_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

func (x *Element) GetImage() *Element_Image {
	if x, ok := x.GetElement().(*Element_Image_); ok {
		return x.Image
	}
	return nil
}

func (x *Element) GetText() *Element_Text {
	if x, ok := x.GetElement().(*Element_Text_); ok {
		return x.Text
	}
	return nil
}

func (x *Element) GetRichText() *Element_RichText {
	if x, ok := x.GetElement().(*Element_RichText_); ok {
		return x.RichText
	}
	return nil
}

type isElement_Element interface {
	isElement_Element()
}

type Element_Image_ struct {
	Image *Element_Image `protobuf:"bytes,1,opt,name=image,proto3,oneof"`
}

type Element_Text_ struct {
	Text *Element_Text `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type Element_RichText_ struct {
	RichText *Element_RichText `protobuf:"bytes,3,opt,name=richText,proto3,oneof"`
}

func (*Element_Image_) isElement_Element() {}

func (*Element_Text_) isElement_Element() {}

func (*Element_RichText_) isElement_Element() {}

type Block_Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *Block_Author) Reset() {
	*x = Block_Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block_Author) ProtoMessage() {}

func (x *Block_Author) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block_Author.ProtoReflect.Descriptor instead.
func (*Block_Author) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Block_Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block_Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Block_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type BlockMeta_Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *BlockMeta_Author) Reset() {
	*x = BlockMeta_Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockMeta_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta_Author) ProtoMessage() {}

func (x *BlockMeta_Author) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta_Author.ProtoReflect.Descriptor instead.
func (*BlockMeta_Author) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BlockMeta_Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockMeta_Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlockMeta_Author) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type BlockRules_CommentRules struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nested    *bool  `protobuf:"varint,1,opt,name=nested,proto3,oneof" json:"nested,omitempty"`
	HasLikes  *bool  `protobuf:"varint,2,opt,name=has_likes,json=hasLikes,proto3,oneof" json:"has_likes,omitempty"`
	Editable  *bool  `protobuf:"varint,3,opt,name=editable,proto3,oneof" json:"editable,omitempty"`
	MaxNested *int32 `protobuf:"varint,4,opt,name=max_nested,json=maxNested,proto3,oneof" json:"max_nested,omitempty"`
}

func (x *BlockRules_CommentRules) Reset() {
	*x = BlockRules_CommentRules{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRules_CommentRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRules_CommentRules) ProtoMessage() {}

func (x *BlockRules_CommentRules) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRules_CommentRules.ProtoReflect.Descriptor instead.
func (*BlockRules_CommentRules) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BlockRules_CommentRules) GetNested() bool {
	if x != nil && x.Nested != nil {
		return *x.Nested
	}
	return false
}

func (x *BlockRules_CommentRules) GetHasLikes() bool {
	if x != nil && x.HasLikes != nil {
		return *x.HasLikes
	}
	return false
}

func (x *BlockRules_CommentRules) GetEditable() bool {
	if x != nil && x.Editable != nil {
		return *x.Editable
	}
	return false
}

func (x *BlockRules_CommentRules) GetMaxNested() int32 {
	if x != nil && x.MaxNested != nil {
		return *x.MaxNested
	}
	return 0
}

type Element_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	File  string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Alt   string `protobuf:"bytes,3,opt,name=alt,proto3" json:"alt,omitempty"`
}

func (x *Element_Image) Reset() {
	*x = Element_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element_Image) ProtoMessage() {}

func (x *Element_Image) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element_Image.ProtoReflect.Descriptor instead.
func (*Element_Image) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Element_Image) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Element_Image) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Element_Image) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

type Element_RichText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Hint    string `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *Element_RichText) Reset() {
	*x = Element_RichText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element_RichText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element_RichText) ProtoMessage() {}

func (x *Element_RichText) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element_RichText.ProtoReflect.Descriptor instead.
func (*Element_RichText) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Element_RichText) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Element_RichText) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Element_RichText) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type Element_Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Hint    string `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *Element_Text) Reset() {
	*x = Element_Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Shared_proto_block_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Element_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element_Text) ProtoMessage() {}

func (x *Element_Text) ProtoReflect() protoreflect.Message {
	mi := &file_Shared_proto_block_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element_Text.ProtoReflect.Descriptor instead.
func (*Element_Text) Descriptor() ([]byte, []int) {
	return file_Shared_proto_block_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Element_Text) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Element_Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Element_Text) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

var File_Shared_proto_block_proto protoreflect.FileDescriptor

var file_Shared_proto_block_proto_rawDesc = []byte{
	0x0a, 0x18, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc4, 0x02, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x73, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x1a, 0x42, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x1a, 0x42, 0x0a, 0x06, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x99,
	0x03, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x20, 0x0a,
	0x09, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x08, 0x68, 0x61, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x26, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12, 0x47, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x48, 0x02, 0x52,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x88, 0x01, 0x01,
	0x1a, 0xc7, 0x01, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x1b, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x20,
	0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x01, 0x52, 0x08, 0x68, 0x61, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x88, 0x01, 0x01,
	0x12, 0x1f, 0x0a, 0x08, 0x65, 0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x02, 0x52, 0x08, 0x65, 0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x22, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x6d, 0x61, 0x78, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x68,
	0x61, 0x73, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x68, 0x61, 0x73,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x81, 0x03, 0x0a, 0x07, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x35, 0x0a, 0x08, 0x72, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x52, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x08, 0x72, 0x69,
	0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x43, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x1a, 0x4c, 0x0a, 0x08, 0x52,
	0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x1a, 0x48, 0x0a, 0x04, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x69, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Shared_proto_block_proto_rawDescOnce sync.Once
	file_Shared_proto_block_proto_rawDescData = file_Shared_proto_block_proto_rawDesc
)

func file_Shared_proto_block_proto_rawDescGZIP() []byte {
	file_Shared_proto_block_proto_rawDescOnce.Do(func() {
		file_Shared_proto_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_Shared_proto_block_proto_rawDescData)
	})
	return file_Shared_proto_block_proto_rawDescData
}

var file_Shared_proto_block_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_Shared_proto_block_proto_goTypes = []interface{}{
	(*Block)(nil),                   // 0: proto.Block
	(*BlockContent)(nil),            // 1: proto.BlockContent
	(*BlockMeta)(nil),               // 2: proto.BlockMeta
	(*BlockRules)(nil),              // 3: proto.BlockRules
	(*Element)(nil),                 // 4: proto.Element
	(*Block_Author)(nil),            // 5: proto.Block.Author
	(*BlockMeta_Author)(nil),        // 6: proto.BlockMeta.Author
	(*BlockRules_CommentRules)(nil), // 7: proto.BlockRules.CommentRules
	(*Element_Image)(nil),           // 8: proto.Element.Image
	(*Element_RichText)(nil),        // 9: proto.Element.RichText
	(*Element_Text)(nil),            // 10: proto.Element.Text
}
var file_Shared_proto_block_proto_depIdxs = []int32{
	5,  // 0: proto.Block.authors:type_name -> proto.Block.Author
	4,  // 1: proto.Block.content:type_name -> proto.Element
	3,  // 2: proto.Block.rules:type_name -> proto.BlockRules
	4,  // 3: proto.BlockContent.content:type_name -> proto.Element
	6,  // 4: proto.BlockMeta.authors:type_name -> proto.BlockMeta.Author
	7,  // 5: proto.BlockRules.commentRules:type_name -> proto.BlockRules.CommentRules
	8,  // 6: proto.Element.image:type_name -> proto.Element.Image
	10, // 7: proto.Element.text:type_name -> proto.Element.Text
	9,  // 8: proto.Element.richText:type_name -> proto.Element.RichText
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_Shared_proto_block_proto_init() }
func file_Shared_proto_block_proto_init() {
	if File_Shared_proto_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Shared_proto_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block_Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockMeta_Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRules_CommentRules); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element_RichText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Shared_proto_block_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Element_Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_Shared_proto_block_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_Shared_proto_block_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Element_Image_)(nil),
		(*Element_Text_)(nil),
		(*Element_RichText_)(nil),
	}
	file_Shared_proto_block_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Shared_proto_block_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Shared_proto_block_proto_goTypes,
		DependencyIndexes: file_Shared_proto_block_proto_depIdxs,
		MessageInfos:      file_Shared_proto_block_proto_msgTypes,
	}.Build()
	File_Shared_proto_block_proto = out.File
	file_Shared_proto_block_proto_rawDesc = nil
	file_Shared_proto_block_proto_goTypes = nil
	file_Shared_proto_block_proto_depIdxs = nil
}
