// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Block struct {
	ID               uuid.UUID
	Name             string
	CreatedAt        sql.NullTime
	Author           uuid.UUID
	RulesName        sql.NullString
	Nested           bool
	HasLikes         bool
	HasComments      bool
	CommentsMaxNest  int16
	CommentsHasLikes bool
	CommentEditable  bool
	Type             int32
}

type BlockCateg struct {
	BlockID uuid.UUID
	CategID int32
}

type BlockImage struct {
	ID          int32
	File        string
	Alt         sql.NullString
	Title       string
	BlockLangID int32
}

type BlockLang struct {
	ID            int32
	LangName      string
	LangCode      string
	VersionNumber sql.NullInt32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	BlockID       uuid.UUID
}

type BlockNested struct {
	Parent uuid.NullUUID
	Child  uuid.NullUUID
}

type BlockRichText struct {
	ID          int32
	Content     string
	Name        string
	Hint        sql.NullString
	BlockLangID int32
}

type BlockRule struct {
	ID               int32
	Name             string
	Descr            string
	Nested           sql.NullBool
	HasComments      sql.NullBool
	HasLikes         sql.NullBool
	CommentsMaxNest  sql.NullInt16
	CommentsHasLikes sql.NullBool
	CommentEditable  sql.NullBool
}

type BlockTag struct {
	BlockID uuid.UUID
	TagID   int32
}

type BlockText struct {
	ID          int32
	Content     string
	Name        string
	Hint        sql.NullString
	BlockLangID int32
}

type BlockType struct {
	ID    int32
	Name  string
	Descr sql.NullString
}

type Category struct {
	ID    int32
	Name  string
	Descr sql.NullString
}

type Tag struct {
	ID    int32
	Name  string
	Descr sql.NullString
}
