// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Block struct {
	ID            uuid.UUID
	HasComments   sql.NullBool
	HasLikes      sql.NullBool
	VersionNumber interface{}
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Author        uuid.UUID
	BlockType     uuid.NullUUID
	CommentsType  uuid.NullUUID
}

type BlockCateg struct {
	BlockID uuid.NullUUID
	CategID uuid.NullUUID
}

type BlockImage struct {
	ID          int32
	BlockLangID sql.NullInt32
	File        string
	Alt         sql.NullString
	Title       string
}

type BlockLang struct {
	ID       int32
	BlockID  uuid.UUID
	LangName string
	LangCode string
}

type BlockNested struct {
	Parent uuid.NullUUID
	Child  uuid.NullUUID
}

type BlockRichText struct {
	ID          int32
	BlockLangID sql.NullInt32
	Content     string
	Name        string
	Hint        sql.NullString
}

type BlockTag struct {
	BlockID uuid.NullUUID
	TagID   uuid.NullUUID
}

type BlockText struct {
	ID          int32
	BlockLangID sql.NullInt32
	Content     string
	Name        string
	Hint        sql.NullString
}

type BlockType struct {
	ID          uuid.UUID
	HasComments sql.NullBool
	HasLikes    sql.NullBool
	Name        sql.NullString
}

type Category struct {
	ID    uuid.UUID
	Name  string
	Descr sql.NullString
}

type CommentType struct {
	ID       uuid.UUID
	Nested   sql.NullBool
	MaxNest  sql.NullInt16
	HasLikes sql.NullBool
	Editable sql.NullBool
}

type Tag struct {
	ID    uuid.UUID
	Name  string
	Descr sql.NullString
}
