// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addBlock = `-- name: AddBlock :one

INSERT INTO blocks (author, name, nested, has_likes, has_comments, comments_max_nest,
                           comments_has_likes, comment_editable, rules_name, type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id
`

type AddBlockParams struct {
	Author           uuid.UUID
	Name             string
	Nested           bool
	HasLikes         bool
	HasComments      bool
	CommentsMaxNest  int16
	CommentsHasLikes bool
	CommentEditable  bool
	RulesName        sql.NullString
	Type             int32
}

// ----------------
// 2- Adding
// ----------------
func (q *Queries) AddBlock(ctx context.Context, arg AddBlockParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addBlock,
		arg.Author,
		arg.Name,
		arg.Nested,
		arg.HasLikes,
		arg.HasComments,
		arg.CommentsMaxNest,
		arg.CommentsHasLikes,
		arg.CommentEditable,
		arg.RulesName,
		arg.Type,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const addBlockRules = `-- name: AddBlockRules :one
INSERT INTO block_rules (
    name, nested, has_likes, has_comments, comments_max_nest,
    comments_has_likes, comment_editable)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING name
`

type AddBlockRulesParams struct {
	Name             string
	Nested           sql.NullBool
	HasLikes         sql.NullBool
	HasComments      sql.NullBool
	CommentsMaxNest  sql.NullInt16
	CommentsHasLikes sql.NullBool
	CommentEditable  sql.NullBool
}

func (q *Queries) AddBlockRules(ctx context.Context, arg AddBlockRulesParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addBlockRules,
		arg.Name,
		arg.Nested,
		arg.HasLikes,
		arg.HasComments,
		arg.CommentsMaxNest,
		arg.CommentsHasLikes,
		arg.CommentEditable,
	)
	var name string
	err := row.Scan(&name)
	return name, err
}

const addCateg = `-- name: AddCateg :one
INSERT INTO categories (
    name, descr
) VALUES ($1,$2) RETURNING name
`

type AddCategParams struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) AddCateg(ctx context.Context, arg AddCategParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addCateg, arg.Name, arg.Descr)
	var name string
	err := row.Scan(&name)
	return name, err
}

const addTag = `-- name: AddTag :one
INSERT INTO tags (
    name, descr
) VALUES ($1,$2) RETURNING name
`

type AddTagParams struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) AddTag(ctx context.Context, arg AddTagParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addTag, arg.Name, arg.Descr)
	var name string
	err := row.Scan(&name)
	return name, err
}

const deleteAllBlockCategs = `-- name: DeleteAllBlockCategs :exec
DELETE FROM block_categs
WHERE block_id = $1
`

func (q *Queries) DeleteAllBlockCategs(ctx context.Context, blockID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllBlockCategs, blockID)
	return err
}

const deleteAllBlockTags = `-- name: DeleteAllBlockTags :exec
DELETE FROM block_tags
WHERE block_id = $1
`

func (q *Queries) DeleteAllBlockTags(ctx context.Context, blockID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllBlockTags, blockID)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec

DELETE FROM blocks WHERE id = $1
`

// ----------------
// 6- Deletions
// ----------------
func (q *Queries) DeleteBlock(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, id)
	return err
}

const deleteBlockCateg = `-- name: DeleteBlockCateg :exec
DELETE FROM block_categs
WHERE block_id = $1 AND
    categ_id = (
        SELECT id
        FROM categories
        WHERE name = $2
    )
`

type DeleteBlockCategParams struct {
	BlockID uuid.UUID
	Name    string
}

func (q *Queries) DeleteBlockCateg(ctx context.Context, arg DeleteBlockCategParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockCateg, arg.BlockID, arg.Name)
	return err
}

const deleteBlockImages = `-- name: DeleteBlockImages :exec
DELETE FROM block_images
WHERE block_lang_id = (
        SELECT id
        FROM  block_langs
        WHERE block_id = $1 AND lang_name = $2
    )
`

type DeleteBlockImagesParams struct {
	BlockID  uuid.UUID
	LangName string
}

func (q *Queries) DeleteBlockImages(ctx context.Context, arg DeleteBlockImagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockImages, arg.BlockID, arg.LangName)
	return err
}

const deleteBlockLang = `-- name: DeleteBlockLang :exec
DELETE FROM block_langs
WHERE block_id = $1 AND lang_name = $2
`

type DeleteBlockLangParams struct {
	BlockID  uuid.UUID
	LangName string
}

func (q *Queries) DeleteBlockLang(ctx context.Context, arg DeleteBlockLangParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockLang, arg.BlockID, arg.LangName)
	return err
}

const deleteBlockRichText = `-- name: DeleteBlockRichText :exec
DELETE FROM block_rich_texts
WHERE block_lang_id = (
        SELECT id
        FROM  block_langs
        WHERE block_id = $1 AND lang_name = $2
    )
`

type DeleteBlockRichTextParams struct {
	BlockID  uuid.UUID
	LangName string
}

func (q *Queries) DeleteBlockRichText(ctx context.Context, arg DeleteBlockRichTextParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockRichText, arg.BlockID, arg.LangName)
	return err
}

const deleteBlockTag = `-- name: DeleteBlockTag :exec
DELETE FROM block_tags
WHERE block_id = $1 AND
    tag_id = (
        SELECT id
        FROM tags
        WHERE name = $2
    )
`

type DeleteBlockTagParams struct {
	BlockID uuid.UUID
	Name    string
}

func (q *Queries) DeleteBlockTag(ctx context.Context, arg DeleteBlockTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockTag, arg.BlockID, arg.Name)
	return err
}

const deleteBlockText = `-- name: DeleteBlockText :exec
DELETE FROM block_texts
WHERE block_lang_id = (
        SELECT id
        FROM  block_langs
        WHERE block_id = $1 AND lang_name = $2
    )
`

type DeleteBlockTextParams struct {
	BlockID  uuid.UUID
	LangName string
}

func (q *Queries) DeleteBlockText(ctx context.Context, arg DeleteBlockTextParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockText, arg.BlockID, arg.LangName)
	return err
}

const deleteCategByID = `-- name: DeleteCategByID :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategByID, id)
	return err
}

const deleteTagByID = `-- name: DeleteTagByID :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTagByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTagByID, id)
	return err
}

const getAllBlockRules = `-- name: GetAllBlockRules :many
SELECT name, descr
FROM block_rules
LIMIT 100
`

type GetAllBlockRulesRow struct {
	Name  string
	Descr string
}

func (q *Queries) GetAllBlockRules(ctx context.Context) ([]GetAllBlockRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlockRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBlockRulesRow
	for rows.Next() {
		var i GetAllBlockRulesRow
		if err := rows.Scan(&i.Name, &i.Descr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT name, descr
FROM categories
LIMIT 100
`

type GetAllCategoriesRow struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) GetAllCategories(ctx context.Context) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesRow
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(&i.Name, &i.Descr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
SELECT name, descr
FROM tags
LIMIT 100
`

type GetAllTagsRow struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) GetAllTags(ctx context.Context) ([]GetAllTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTagsRow
	for rows.Next() {
		var i GetAllTagsRow
		if err := rows.Scan(&i.Name, &i.Descr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlock = `-- name: GetBlock :many


SELECT id, author, created_at, name
FROM blocks
LIMIT $1
OFFSET $2
`

type GetBlockParams struct {
	Limit  int32
	Offset int32
}

type GetBlockRow struct {
	ID        uuid.UUID
	Author    uuid.UUID
	CreatedAt sql.NullTime
	Name      string
}

//	 ____                  _
//	/ __ \__  _____  _____(_)__  _____
//
// / / / / / / / _ \/ ___/ / _ \/ ___/
// / /_/ / /_/ /  __/ /  / /  __(__  )
// \___\_\__,_/\___/_/  /_/\___/____/
// ------------------------------------------
// This File Contains all Queries on the Main Database.
// Refer to Sqlc for more information https://docs.sqlc.dev/en/stable/
//
// The File Includes 6 Section:
//
// 1- `Selections` following: Get? / Get?By?
// 2- `Adding` Inserts following Create?
// 3- `Joins` insert for ManyToMany, following Add?To?
// 4- `Updates` following: Update?
// 5- `Deletions` following: Delete?
// 6- `Counts` following: Count?
//
// Please use PascalCase for naming.
// ----------------
// 1- Selections
// ----------------
func (q *Queries) GetBlock(ctx context.Context, arg GetBlockParams) ([]GetBlockRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlock, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockRow
	for rows.Next() {
		var i GetBlockRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.CreatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockByID = `-- name: GetBlockByID :one
SELECT id, author, created_at, name
FROM blocks b
WHERE b.id = $1
`

type GetBlockByIDRow struct {
	ID        uuid.UUID
	Author    uuid.UUID
	CreatedAt sql.NullTime
	Name      string
}

func (q *Queries) GetBlockByID(ctx context.Context, id uuid.UUID) (GetBlockByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBlockByID, id)
	var i GetBlockByIDRow
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}

const getBlockCategories = `-- name: GetBlockCategories :many
SELECT c.name
FROM categories c
INNER JOIN block_categs bc
ON c.id = bc.categ_id
WHERE bc.block_id = $1
LIMIT 100
`

func (q *Queries) GetBlockCategories(ctx context.Context, blockID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockCategories, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockImages = `-- name: GetBlockImages :many
select bi.title, bi.alt, bi.file
from block_images bi
inner join block_langs bl
on block_lang.id = bi.block_lang_id
where bl.lang_code = $1 and  bl.block_id = $2
`

type GetBlockImagesParams struct {
	LangCode string
	BlockID  uuid.UUID
}

type GetBlockImagesRow struct {
	Title string
	Alt   sql.NullString
	File  string
}

func (q *Queries) GetBlockImages(ctx context.Context, arg GetBlockImagesParams) ([]GetBlockImagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockImages, arg.LangCode, arg.BlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockImagesRow
	for rows.Next() {
		var i GetBlockImagesRow
		if err := rows.Scan(&i.Title, &i.Alt, &i.File); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockRichText = `-- name: GetBlockRichText :many
select brt.name, brt.hint, brt.content
from block_rich_texts brt
inner join block_langs bl
on bl.id = brt.block_lang_id
where bl.lang_code = $1 and  bl.block_id = $2
`

type GetBlockRichTextParams struct {
	LangCode string
	BlockID  uuid.UUID
}

type GetBlockRichTextRow struct {
	Name    string
	Hint    sql.NullString
	Content string
}

func (q *Queries) GetBlockRichText(ctx context.Context, arg GetBlockRichTextParams) ([]GetBlockRichTextRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockRichText, arg.LangCode, arg.BlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockRichTextRow
	for rows.Next() {
		var i GetBlockRichTextRow
		if err := rows.Scan(&i.Name, &i.Hint, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockRulesByName = `-- name: GetBlockRulesByName :one
SELECT nested, has_comments, has_likes,
    comments_max_nest, comments_has_likes, comment_editable
FROM block_rules
WHERE name = $1
`

type GetBlockRulesByNameRow struct {
	Nested           sql.NullBool
	HasComments      sql.NullBool
	HasLikes         sql.NullBool
	CommentsMaxNest  sql.NullInt16
	CommentsHasLikes sql.NullBool
	CommentEditable  sql.NullBool
}

func (q *Queries) GetBlockRulesByName(ctx context.Context, name string) (GetBlockRulesByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getBlockRulesByName, name)
	var i GetBlockRulesByNameRow
	err := row.Scan(
		&i.Nested,
		&i.HasComments,
		&i.HasLikes,
		&i.CommentsMaxNest,
		&i.CommentsHasLikes,
		&i.CommentEditable,
	)
	return i, err
}

const getBlockTags = `-- name: GetBlockTags :many
SELECT t.name
FROM tags t
INNER JOIN block_tags bt
ON t.id = bt.tag_id
WHERE bt.block_id = $1
LIMIT 100
`

func (q *Queries) GetBlockTags(ctx context.Context, blockID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockTags, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockText = `-- name: GetBlockText :many
select bt.content, bt.hint, bt.name
from block_texts bt
inner join block_langs bl
on bl.id = bt.block_lang_id
where bl.lang_code = $1 and  bl.block_id = $2
`

type GetBlockTextParams struct {
	LangCode string
	BlockID  uuid.UUID
}

type GetBlockTextRow struct {
	Content string
	Hint    sql.NullString
	Name    string
}

func (q *Queries) GetBlockText(ctx context.Context, arg GetBlockTextParams) ([]GetBlockTextRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockText, arg.LangCode, arg.BlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockTextRow
	for rows.Next() {
		var i GetBlockTextRow
		if err := rows.Scan(&i.Content, &i.Hint, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTypeByName = `-- name: GetTypeByName :one
SELECT id
FROM block_types bt
WHERE bt.name = $1
`

func (q *Queries) GetTypeByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTypeByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const joinCategToBlock = `-- name: JoinCategToBlock :exec
INSERT INTO block_categs(
    block_id, categ_id
) VALUES ($1,$2)
`

type JoinCategToBlockParams struct {
	BlockID uuid.UUID
	CategID int32
}

func (q *Queries) JoinCategToBlock(ctx context.Context, arg JoinCategToBlockParams) error {
	_, err := q.db.ExecContext(ctx, joinCategToBlock, arg.BlockID, arg.CategID)
	return err
}

const joinChildToBlock = `-- name: JoinChildToBlock :exec
INSERT INTO block_nested (
    child, parent
) VALUES ($1,$2)
`

type JoinChildToBlockParams struct {
	Child  uuid.NullUUID
	Parent uuid.NullUUID
}

func (q *Queries) JoinChildToBlock(ctx context.Context, arg JoinChildToBlockParams) error {
	_, err := q.db.ExecContext(ctx, joinChildToBlock, arg.Child, arg.Parent)
	return err
}

const joinTagToBlock = `-- name: JoinTagToBlock :exec

INSERT INTO block_tags(
    block_id, tag_id
) VALUES ($1,$2)
`

type JoinTagToBlockParams struct {
	BlockID uuid.UUID
	TagID   int32
}

// ----------------
// 3- Joins
// ----------------
func (q *Queries) JoinTagToBlock(ctx context.Context, arg JoinTagToBlockParams) error {
	_, err := q.db.ExecContext(ctx, joinTagToBlock, arg.BlockID, arg.TagID)
	return err
}

const updateBlockRules = `-- name: UpdateBlockRules :exec

Update blocks
    SET rules_name = $2,
        nested = $3,
        has_likes = $4,
        has_comments = $5,
        comments_max_nest = $6,
        comments_has_likes = $7,
        comment_editable = $8
WHERE name = $1
`

type UpdateBlockRulesParams struct {
	Name             string
	RulesName        sql.NullString
	Nested           bool
	HasLikes         bool
	HasComments      bool
	CommentsMaxNest  int16
	CommentsHasLikes bool
	CommentEditable  bool
}

// ----------------
// 5- Updates
// ----------------
func (q *Queries) UpdateBlockRules(ctx context.Context, arg UpdateBlockRulesParams) error {
	_, err := q.db.ExecContext(ctx, updateBlockRules,
		arg.Name,
		arg.RulesName,
		arg.Nested,
		arg.HasLikes,
		arg.HasComments,
		arg.CommentsMaxNest,
		arg.CommentsHasLikes,
		arg.CommentEditable,
	)
	return err
}
