// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: taxonomy.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addCateg = `-- name: AddCateg :one
INSERT INTO categories (
    name, descr
) VALUES ($1,$2) RETURNING name
`

type AddCategParams struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) AddCateg(ctx context.Context, arg AddCategParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addCateg, arg.Name, arg.Descr)
	var name string
	err := row.Scan(&name)
	return name, err
}

const addTag = `-- name: AddTag :one

INSERT INTO tags (
    name, descr
) VALUES ($1,$2) RETURNING name
`

type AddTagParams struct {
	Name  string
	Descr sql.NullString
}

// ----------------
// 2- Adding
// ----------------
func (q *Queries) AddTag(ctx context.Context, arg AddTagParams) (string, error) {
	row := q.db.QueryRowContext(ctx, addTag, arg.Name, arg.Descr)
	var name string
	err := row.Scan(&name)
	return name, err
}

const deleteAllBlockCategs = `-- name: DeleteAllBlockCategs :exec
DELETE FROM block_categs
WHERE block_id = $1
`

func (q *Queries) DeleteAllBlockCategs(ctx context.Context, blockID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllBlockCategs, blockID)
	return err
}

const deleteAllBlockTags = `-- name: DeleteAllBlockTags :exec
DELETE FROM block_tags
WHERE block_id = $1
`

func (q *Queries) DeleteAllBlockTags(ctx context.Context, blockID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllBlockTags, blockID)
	return err
}

const deleteBlockCateg = `-- name: DeleteBlockCateg :exec



DELETE FROM block_categs
WHERE block_id = $1 AND
    categ_id = (
        SELECT id
        FROM categories
        WHERE name = $2
    )
`

type DeleteBlockCategParams struct {
	BlockID uuid.UUID
	Name    string
}

// ----------------
// 3- Joins
// ----------------
// ----------------
// 5- Updates
// ----------------
// ----------------
// 6- Deletions
// ----------------
func (q *Queries) DeleteBlockCateg(ctx context.Context, arg DeleteBlockCategParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockCateg, arg.BlockID, arg.Name)
	return err
}

const deleteBlockTag = `-- name: DeleteBlockTag :exec
DELETE FROM block_tags
WHERE block_id = $1 AND
    tag_id = (
        SELECT id
        FROM tags
        WHERE name = $2
    )
`

type DeleteBlockTagParams struct {
	BlockID uuid.UUID
	Name    string
}

func (q *Queries) DeleteBlockTag(ctx context.Context, arg DeleteBlockTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockTag, arg.BlockID, arg.Name)
	return err
}

const deleteCategByID = `-- name: DeleteCategByID :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategByID, id)
	return err
}

const deleteTagByID = `-- name: DeleteTagByID :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTagByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTagByID, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT name, descr
FROM categories
LIMIT 100
`

type GetAllCategoriesRow struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) GetAllCategories(ctx context.Context) ([]GetAllCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCategoriesRow
	for rows.Next() {
		var i GetAllCategoriesRow
		if err := rows.Scan(&i.Name, &i.Descr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTags = `-- name: GetAllTags :many
SELECT name, descr
FROM tags
LIMIT 100
`

type GetAllTagsRow struct {
	Name  string
	Descr sql.NullString
}

func (q *Queries) GetAllTags(ctx context.Context) ([]GetAllTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTagsRow
	for rows.Next() {
		var i GetAllTagsRow
		if err := rows.Scan(&i.Name, &i.Descr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockCategories = `-- name: GetBlockCategories :many


SELECT c.name
FROM categories c
INNER JOIN block_categs bc
ON c.id = bc.categ_id
WHERE bc.block_id = $1
LIMIT 100
`

//	 ____                  _
//	/ __ \__  _____  _____(_)__  _____
//
// / / / / / / / _ \/ ___/ / _ \/ ___/
// / /_/ / /_/ /  __/ /  / /  __(__  )
// \___\_\__,_/\___/_/  /_/\___/____/
// ------------------------------------------
// This File Contains all Queries on the Main Database.
// Refer to Sqlc for more information https://docs.sqlc.dev/en/stable/
//
// The File Includes 6 Section:
//
// 1- `Selections` following: Get? / Get?By?
// 2- `Adding` Inserts following Create?
// 3- `Joins` insert for ManyToMany, following Add?To?
// 4- `Updates` following: Update?
// 5- `Deletions` following: Delete?
// 6- `Counts` following: Count?
//
// Please use PascalCase for naming.
// ----------------
// 1- Selections
// ----------------
func (q *Queries) GetBlockCategories(ctx context.Context, blockID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockCategories, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockTags = `-- name: GetBlockTags :many
SELECT t.name
FROM tags t
INNER JOIN block_tags bt
ON t.id = bt.tag_id
WHERE bt.block_id = $1
LIMIT 100
`

func (q *Queries) GetBlockTags(ctx context.Context, blockID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getBlockTags, blockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinCategToBlock = `-- name: JoinCategToBlock :exec
INSERT INTO block_categs(
    block_id, categ_id
) VALUES ($1,$2)
`

type JoinCategToBlockParams struct {
	BlockID uuid.UUID
	CategID int32
}

func (q *Queries) JoinCategToBlock(ctx context.Context, arg JoinCategToBlockParams) error {
	_, err := q.db.ExecContext(ctx, joinCategToBlock, arg.BlockID, arg.CategID)
	return err
}

const joinTagToBlock = `-- name: JoinTagToBlock :exec

INSERT INTO block_tags(
    block_id, tag_id
) VALUES ($1,$2)
`

type JoinTagToBlockParams struct {
	BlockID uuid.UUID
	TagID   int32
}

// ----------------
// 3- Joins
// ----------------
func (q *Queries) JoinTagToBlock(ctx context.Context, arg JoinTagToBlockParams) error {
	_, err := q.db.ExecContext(ctx, joinTagToBlock, arg.BlockID, arg.TagID)
	return err
}
